name: Build

on:
  push:
  pull_request:

jobs:
  lint:
    name: Install & Lint
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
        with:
          submodules: true
      -
        name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      -
        id: install
        run: yarn install
      -
        id: lint
        run: yarn lint

  deploy:
    if: github.ref == 'refs/heads/main'
    name: Trigger private build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      -
        # This step is for master builds only
        name: Trigger Docs Deploy to Staging
        id: trigger_staging_deploy
        uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: smallstep
          repo:  prof
          github_token: ${{ secrets.PAT }}
          workflow_file_name: deploy.yml
          ref: master
          waiting_interval: 30

